name: dhall

on: [push, pull_request, workflow_dispatch]

jobs:
  dhall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dhall-lang/setup-dhall@v4
      - run: set -e; for f in $GITHUB_WORKSPACE/**/*.dhall; do dhall --file $f; done
