name: YAML schema validator using Yamale
on: [push, pull_request, workflow_dispatch]

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: NCATS-Tangerine/yaml-schema-validator-github-action@master
      with:
        schema: '../schema/mapping.yaml'
        target: 'config/mappings.yml'
        strict: '1'
    - uses: NCATS-Tangerine/yaml-schema-validator-github-action@master
      with:
        schema: '../schema/features.yaml'
        target: 'config/all_features.yaml'
        strict: '1'
    - uses: NCATS-Tangerine/yaml-schema-validator-github-action@master
      with:
        schema: '../schema/identifiers.yaml'
        target: 'config/identifiers.yml'
        strict: '1'
    - uses: NCATS-Tangerine/yaml-schema-validator-github-action@master
      with:
        schema: '../schema/sets.yaml'
        target: 'config/value_sets.yaml'
        strict: '1'
