name: YAML schema validator
on: [push, pull_request, workflow_dispatch]

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nrkno/yaml-schema-validator-github-action@6cf8c4b3bceea7928c91432e865dcdc46fa4419c
      with:
        schema: ../schema/mapping.yaml
        target: config/mappings.yml
        strict: '1'
    - uses: nrkno/yaml-schema-validator-github-action@6cf8c4b3bceea7928c91432e865dcdc46fa4419c
      with:
        schema: ../schema/features.yaml
        target: config/all_features.yaml
        strict: '1'
